describe('Filter all one by one', ()=> {
  beforeEach( ()=> {
    cy.visit("https://practicesoftwaretesting.com/#/")
  })
  it('Hammer', ()=> {
    cy.getByData('category-01HGQW7HEC1KWXQZNM96JS2H1W').check()
    cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
    cy.get('h5').contains('Court').should('exist')
    cy.getByData('category-01HGQW7HEC1KWXQZNM96JS2H1W').uncheck()
    cy.get('h5').contains('Pliers').should('exist')
    cy.get('h5').contains('Hammer').should('exist')
    cy.get('h5').contains('Court').should('not.exist')
  })
  // it('Hand Saw', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZG').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Wood Saw').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZG').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Wood Saw').should('not.exist')
  // })
  // it('Wrench', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZH').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Wrench').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZH').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Wrench').should('not.exist')
  // })
  // it('Screwdriver', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZJ').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Screwdriver').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZJ').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Screwdriver').should('not.exist')
  // })
  // it('Pliers', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZK').check()
  //   cy.get('h5').contains('Hammer').should('not.exist')
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZK').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  // })
  // it('Drill', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZQ').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Drill').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZQ').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Drill').should('not.exist')
  // })
  // it('Grinder', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZM').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.contains('No results found.').should('be.visible')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZM').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  // })
  // it('Sander', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZN').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Sander').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZN').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Sander').should('not.exist')
  // })
  // it('Saw', ()=> {
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZP').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.get('h5').contains('Saw').should('exist')
  //   cy.getByData('category-01HGP59P04DMBQ4KCWG1VF99ZP').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  //   cy.get('h5').contains('Saw').should('not.exist')
  // })
  // it('Brand name 1', ()=> {
  //   cy.getByData('brand-01HGP59NZTVR3JAHXJ5147TQ5D').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.getByData('brand-01HGP59NZTVR3JAHXJ5147TQ5D').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  // })
  // it('Brand name 2', ()=> {
  //   cy.getByData('brand-01HGP59NZTVR3JAHXJ5147TQ5E').check()
  //   cy.get('h5').contains('Pliers', 'Hammer').should('not.exist')
  //   cy.contains('No results found.').should('be.visible')
  //   cy.getByData('brand-01HGP59NZTVR3JAHXJ5147TQ5E').uncheck()
  //   cy.get('h5').contains('Pliers').should('exist')
  //   cy.get('h5').contains('Hammer').should('exist')
  // })
 })

