import { contains } from "cypress/types/jquery"

describe('Registration page', () => {
  beforeEach( ()=> {
    cy.visit('https://practicesoftwaretesting.com/#/auth/register')
  })
  it('enter invalid email and mobile phone', () => {
    cy.getByData("first-name").type('Nikola')
    cy.getByData("last-name").type('Novosel')
    cy.getByData("dob").type('1989-08-07')
    cy.getByData("address").type('Cetinjska 27')
    cy.getByData("postcode").type('11000')
    cy.getByData("city").type('Belgrade')
    cy.getByData("state").type('Serbia')
    cy.getByData("country").select('Serbia')
    cy.getByData("phone").type('+381603888301')
    cy.getByData("email").type('nikola')
    cy.getByData("password").type('cypress')
    cy.getByData("register-submit").click()
    cy.get('h3').should('contain','Customer registration')
    cy.contains('Only numbers are allowed.').should('be.visible')
    cy.contains('E-mail format is invalid.').should('be.visible')
  })
  it('enter valid data', () => {
    cy.getByData("first-name").type('Nikola')
    cy.getByData("last-name").type('Novosel')
    cy.getByData("dob").type('1989-08-07')
    cy.getByData("address").type('Cetinjska 27')
    cy.getByData("postcode").type('11000')
    cy.getByData("city").type('Belgrade')
    cy.getByData("state").type('Serbia')
    cy.getByData("country").select('Serbia')
    cy.getByData("phone").type('0603888301')
    cy.getByData("email").type('1@gmail.com')
    cy.getByData("password").type('cypress')
    cy.getByData("register-submit").click()
    cy.getByData("success-message").should("not.exist")
    cy.get('h3').contains('Login').should('exist')
  })
})